baseURL = "https://www.clojuriststogether.org"
languageCode = "en-us"
title = "Clojurists Together"
# theme = "ananke"

[markup.goldmark.renderer]
unsafe= true

[params]
custom_css = ["app.css"]

[permalinks]
news = "/news/:slug/"
